var AniCredits = angular.module('AniCredits', []);

AniCredits.controller('DisplayPanel', function ($scope) {
  $scope.events = [
	{'title': 'A Good Librarian Like a Good Shepherd','credit': '©AUGUST・白崎つぐみと迷える子羊たち'},
	{'title': 'Amagi Brilliant Park','credit': '© Kadokawa Corporation 2014'},
	{'title': 'Cardfight!! Vanguard G','credit': '©bushiroad All Rights Reserved.'},
	{'title': 'Celesital Method','credit': '©霧弥湖町観光協会'},
	{'title': 'Chaika the Coffin Princess: Avenging Battle','credit': '©2014 榊一郎・Nitroplus／ＫＡＤＯＫＡＷＡ 富士見書房刊／「棺姫のチャイカAB」製作委員会'},
	{'title': 'Cross Ange Rondo of Angel and Dragon','credit': '© SUNRISE/PROJECT ANGE'},
	{'title': 'Denki-gai no Honya-san','credit': '© 2014 水あさと／株式会社KADOKAWA メディアファクトリー刊／コミックうまのほね'},
	{'title': 'Fate/Stay Night: Unlimited Blade Works','credit': '©TYPE-MOON・ufotable・FSNPC　©TYPE-MOON'},
	{'title': 'Garo: The Carved Seal of Flame','credit': '©2014「炎の刻印」雨宮慶太／東北新社'},
	{'title': 'Girl Friend BETA','credit': 'Copyright © CyberAgent, Inc. All Rights Reserved.'},
	{'title': 'Gonna be the Twin-Tails!!','credit': '©水沢 夢・小学館／製作委員会はツインテールになります。 '},
	{'title': 'Gugure! Kokkuri-san','credit': '©遠藤ミドリ／スクウェアエニックス・「繰繰れ！コックリさん」製作委員会'},
	{'title': 'Gundam Build Fighters Try','credit': '©創通・サンライズ・テレビ東京'},
	{'title': 'Gundam: Reconguista in G','credit': '©創通・サンライズ・ＭＢＳ'},
	{'title': 'Hi☆sCoool! Sega Hard Girl','credit': '©SEGA/セハガガ学園理事会'},
	{'title': 'I Can\'t Understand What My Husband Is Saying','credit': '©クール教信者/一迅社・旦那が製作委員会2014'},
	{'title': 'Laughing Under the Clouds','credit': '© Karakara Kemuri / MAG Garden'},
	{'title': 'Log Horizon','credit': '©橙乃ままれ・KADOKAWA／NHK・NEP'},
	{'title': 'Lord Marksman and Vanadis','credit': '©2014 川口士・株式会社KADOKAWA メディアファクトリー刊／魔弾の王と戦姫製作委員会'},
	{'title': 'Magic Kaito 1412','credit': '©青山剛昌／小学館・読売テレビ・A-1 Pictures 2014'},
	{'title': 'Mushishi: The Next Chapter 2nd Season','credit': '©漆原友紀／講談社・アニプレックス'},
	{'title': 'Ohenro. Eighty-Eight Steps Chronicle','credit': '©ufotable'},
	{'title': 'Parasyte: Probability of Survival','credit': '© 岩明均／講談社・VAP・NTV・4cast'},
	{'title': 'Psycho-Pass','credit': '© PSYCHO-PASS Committee'},
	{'title': 'Rage of Bahamut: Genesis','credit': '© Cygames/MAPPA/BAHAMUT GENESIS'},
	{'title': 'Ronia the Robber\'s Daughter','credit': '©NHK・NEP・Dwango, licensed by Saltkrakan AB, The Astrid Lindgren Company'},
	{'title': 'Searching for the Lost Future','credit': '© Atelier Hi-Key/In Search of the Lost Future production committee'},
	{'title': 'Selector WIXOSS','credit': '©LRIG/Project Selector'},
	{'title': 'SHIROBAKO','credit': '©「SHIROBAKO」製作委員会'},
	{'title': 'Tenchi Muyo! Love','credit': '©梶島正樹／愛・天地無用！'},
	{'title': 'Terra Formars','credit': '©貴家悠・橘賢一／集英社・Project TERRAFORMARS'},
	{'title': 'The Circumstances in My Home\'s Bathtub','credit': '©2014いときち/株式会社KADOKAWA メディアファクトリー刊/オレフロ製作委員会'},
	{'title': 'The Fruit of Grisaia','credit': '©Frontwing/Project GRISAIA'},
	{'title': 'The Seven Deadly Sins','credit': '©鈴木央・講談社／「七つの大罪」製作委員会・MBS'},
	{'title': 'Trinity Seven','credit': '©サイトウケンジ・奈央晃徳／ＫＡＤＯＫＡＷＡ 富士見書房／トリニティセブン製作委員会'},
	{'title': 'When Supernatural Battles Became Commonplace','credit': '©2014　望 公太・ＳＢクリエイティブ／泉光高校文芸部'},
	{'title': 'Wolf Girl and Black Prince','credit': '©八田鮎子／集英社・「オオカミ少女と黒王子」製作委員会'},
	{'title': 'World Trigger','credit': '©葦原大介／集英社・テレビ朝日・東映アニメーション'},
	{'title': 'Yona of the Dawn','credit': '© Mizuho Kusanagi, Hakusensha/Akatsukino Yona Production Committee'},
	{'title': 'Your Lie in April','credit': '©新川直司・講談社／「四月は君の嘘」製作委員会'},
	{'title': 'Yowamushi Pedal: Grande Road','credit': '©渡辺航（週刊少年チャンピオン）／弱虫ペダル製作委員会'},
	{'title': 'Yuuna Yuuki is a Hero','credit': '©2014 Project 2H'},
	{'title': 'Abarenbō Rikishi!! Matsutarō','credit': '© Tetsuya Chiba/TV Asahi, Toei Animation © C/T, T'},
	{'title': 'Baby Steps','credit': '© Hikaru Katsuki, Kodansha/NHK, NEP'},
	{'title': 'Black Bullet','credit': '© 2013 Shiden Kanzaki/Kadokawa/ASCII Media Works/Black Bullet Production Committee'},
	{'title': 'Blade and Soul','credit': '© NCSoft, Blade & Soul Anime Production Committee'},
	{'title': 'Break Blade (TV)','credit': '© Yunosuke Yoshinaga, Flex Comix/Broken Blade Production Committee'},
	{'title': 'Brynhildr in the Darkness','credit': '© Lynn Okamoto/Shueisha, Brynhildr in the Darkness Production Committee'},
	{'title': 'Captain Earth','credit': '©BONES/CAPTAIN EARTH COMMITEE, MBS'},
	{'title': 'Chaika the Coffin Princess','credit': '© Ichiro Sakaki, Namaniku ATK (Nitroplus)'},
	{'title': 'Daimidaler the Sound Robot','credit': '©Asaki Nakama/ENTERBRAIN/PENGUIN EMPIRE'},
	{'title': 'Dai-Shogun - Great Revolution','credit': '©2014 Project-D'},
	{'title': 'Date A Live II','credit': '© 2013 Koushi Tachibana, Tsunako/Fujimi Shobo/Date A Live Production Committee'},
	{'title': 'Dragonar Academy','credit': '©2014 Shiki Mizuchi, PUBLISHED BY KADOKAWA CORPORATION MEDIAFACTORY/Dragonar Project'},
	{'title': 'Haikyuu!!','credit': '© Haruichi Furudate, Shueisha/Haikyuu!! Production Committee'},
	{'title': 'JoJo\'s Bizaare Adventure','credit': '©荒木飛呂彦/集英社・ジョジョの奇妙な冒険製作委員会'},
	{'title': 'Kamigami no Asobi','credit': 'Copyright (C) BROCCOLI'},
	{'title': 'Kindaichi Case Files Returns','credit': '© Seimaru Amagi, Fumiya Sato, Kodansha/YTV, Toei Animation'},
	{'title': 'La Corda d\'Oro -Blue Sky-','credit': '© Yuki Kure, Hakusensha, KOEI Co., Ltd./Corda Production Committee'},
	{'title': 'One Week Friends','credit': '©MATCHA HAZUKI/SQUARE ENIX'},
	{'title': 'Riddle Story of Devil (Akuma no Riddle)','credit': '©高河ゆん・南方純／ＫＡＤＯＫＡＷＡ刊／「悪魔のリドル」製作委員会'},
	{'title': 'The irregular at magic high school','credit': '© Tsutomu Satou / Kadokawa ASCII Media Works Publication / Mahōka Kōkō Production Committee'},
	{'title': 'The Kawai Complex Guide to Manors and Hostel Behavior','credit': '©宮原るり・少年画報社／委員会はみんな河合荘'},
	{'title': 'The World is Still Beautiful','credit': '© Dai Shiina, Hakusensha/Ooshitsu Kaihō Magazine Editorial Department'},
	{'title': 'Ai Mai Mi: Mousou Catastrophe','credit': '© Choboraunyopomi/Takeshobo'},
	{'title': 'Akame ga Kill!','credit': '© タカヒロ・田代哲也／スクウェアエニックス・「アカメが斬る！」製作委員会'},
	{'title': 'Aldnoah.Zero','credit': '© Olympus Knights/Aniplex, Project AZ'},
	{'title': 'Ao Haru Ride','credit': '© 2014 咲坂伊緒／集英社・「アオハライド」製作委員会'},
	{'title': 'Bakumatsu Rock','credit': '© 2014 Marvelous AQL'},
	{'title': 'Barakamon','credit': '©ヨシノサツキ／スクウェアエニックス・「ばらかもん」製作委員会'},
	{'title': 'DRAMAtical Murder','credit': '© Nitroplus／DRAMAtical Murder製作委員会'},
	{'title': 'Fate/kaleid liner Prisma☆Illya 2wei!','credit': '©2014 ひろやまひろし・TYPE-MOON／ＫＡＤＯＫＡＷＡ 角川書店刊／「プリズマ☆イリヤ ツヴァイ！」製作委員会'},
	{'title': 'Free! Eternal Summer','credit': '© Kōji Ōji, Kyoto Animation/Iwatobi High School Swimming Club'},
	{'title': 'Futsuu no Joshikousei ga [Locodol] Yatte Mita.','credit': '©小杉光太郎・一迅社／流川市ふるさと振興課'},
	{'title': 'Gekkan Shoujo Nozaki-kun','credit': '©椿いづみ／スクウェアエニックス・「月刊少女野崎くん」製作委員会'},
	{'title': 'Glasslip','credit': '© glasslip project'},
	{'title': 'Hanamonogatari','credit': '© NISIOISIN/KODANSHA, ANIPLEX, SHAFT'},
	{'title': 'Hanayamata','credit': '©浜弓場 双・芳文社／ハナヤマタ製作委員会'},
	{'title': 'Jinsei','credit': '©川岸殴魚・小学館／人生製作委員会'},
	{'title': 'Kuroshitsuji: Book of Circus','credit': '© 枢やな/スクウェアエニックス・黒執事Project・MBS'},
	{'title': 'Love Stage!!','credit': '©影木栄貴 蔵王大志'},
	{'title': 'Majimoji Rurumo','credit': '© Wataru Watanabe, Kodansha/Magimoji Rurumo Production Committee'},
	{'title': 'Minarai Diva','credit': '© 2014 mmbi,Inc.'},
	{'title': 'Momo Kyun Sword','credit': 'Copyright© Kibidango Project All Rights Reserved.'},
	{'title': 'Nobunaga Concerto','credit': '© 石井あゆみ・小学館／フジテレビジョン'},
	{'title': 'Persona 4 The Golden Animation','credit': 'Copyright (C)ATLUS (C)SEGA/P4GA Committee'},
	{'title': 'Pri Para','credit': '©Ｔ－ＡＲＴＳ / syn Sophia / テレビ東京 / PP製作委員会'},
	{'title': 'RAIL WARS!','credit': '©豊田 巧/創芸社・ProjectRW!'},
	{'title': 'Re:␣Hamatora','credit': '© Café Nowhere/Hamatora Production Committee'},
	{'title': 'Rokujouma no Shinryakusha!?','credit': '©健速・HobbyJAPAN／ころな荘管理組合'},
	{'title': 'Sabagebu!','credit': '© 松本ひで吉・講談社／「さばげぶっ！」製作委員会'},
	{'title': 'Seirei Tsukai no Blade Dance','credit': '©2014 志瑞祐・株式会社KADOKAWA メディアファクトリー刊／精霊使いの剣舞製作委員会'},
	{'title': 'Sengoku Basara: Judge End','credit': '© CAPCOM/BASARA JE'},
	{'title': 'Shirogane no Ishi: Argevollen','credit': '©AIOS/PROJECT ARGEVOLLEN'},
	{'title': 'Shounen Hollywood -Holly Stage for 49-','credit': '© King Records Co., Ltd. © Noel Japan Agency'},
	{'title': 'Space☆Dandy','credit': '© Project SPACE DANDY'},
	{'title': 'Sword Art Online','credit': '©2014 Reki Kawahara / KADOKAWA / ASCII Media Works / SAO II Project'},
	{'title': 'Tokyo ESP','credit': '©2014 瀬川はじめ／KADOKAWA角川書店刊／[東京ESP]製作委員会'},
	{'title': 'Tokyo Ghoul','credit': '©石田スイ／集英社・東京喰種製作委員会'},
	{'title': 'Yama no Susume','credit': '©しろ / アース・スター エンターテイメント'},
	{'title': 'Zankyou no Terror','credit': '©残響のテロル製作委員会 _このホームページに掲載されている一切の文書・図版・写真等を、手段や形態を問わず複製、転載することを禁じます'},
	{'title': 'Kyoukai no Kanata','credit': '© Kyoto Animation'},
	{'title': 'Yuru Yuri','credit': '© Ichijinsha / Dogakobo'},
	{'title': 'Yuru Yuri 3','credit': '© Ichijinsha / TYO Animations'},
	{'title': 'CLANNAD','credit': '© key/Visual Art\'s'},
	{'title': 'Tamako Market','credit': '© Kyoto Animation'},
	{'title': 'Buddy Complex','credit': '©SUNRISE/BUDDY COMPLEX COMMITTEE'},
	{'title': 'Chuunibyou demo Koi ga Shitai!','credit': '© 虎虎／京都アニメーション／中二病でも製作委員会'},
	{'title': 'D-Frag!','credit': '© Tomoya Haruno/PUBLISHED BY KADOKAWA CORPORATION MEDIAFACTORY/D-Fragments Project'},
	{'title': 'Future Card Buddyfight','credit': '© 相棒学園／テレビ愛知'},
	{'title': 'Gin no Saji','credit': '© 荒川弘・小学館／エゾノー祭実行委員会'},
	{'title': 'HappinessCharge Precure!','credit': '©ABC・東映アニメーション'},
	{'title': 'Hamatora','credit': '© カフェノーウェア/ハマトラ製作委員会'},
	{'title': 'Inari, Kon Kon, Koi Iroha','credit': '© 2014 よしだもろへ／KADOKAWA 角川書店刊／いなり製作委員会 / © 京都府 まゆまろ 13176 / © 2013 City of Kyoto. All rights reserved.'},
	{'title': 'Magical Warfare','credit': '© スズキヒサシ／株式会社KADOKAWA　メディアファクトリー刊／すばる魔法学院'},
	{'title': 'Maken-ki Two','credit': '© 2013 Hiromitsu Takeda/PUBLISHED BY KADOKAWA Fujimishobo/MAKEN-KI TWO Partners'},
	{'title': 'Mikakunin DE Shinkoukei','credit': '© 荒井チェリー／一迅社・未確認で進行形製作委員会'},
	{'title': 'Nisekoi','credit': '© 古味直志／集英社・アニプレックス・シャフト・ＭＢＳ'},
	{'title': 'Nobunaga the Fool','credit': '© 河森正治・サテライト／ALC／GP／ノブナガ・ザ・フール製作委員会'},
	{'title': 'Nobunagun','credit': '© 久正人 ／アース・スター エンターテイメント・「ノブナガン製作委員会」'},
	{'title': 'Noragami','credit': '© Adachitoka/Kodansha/Noragami Production Committee'},
	{'title': 'No-rin','credit': '© 2014 白鳥士郎・SBクリエイティブ／のうりんプロジェクト'},
	{'title': 'Saikin, Imouto no Yousu ga Chotto Okashiinda ga.','credit': '© Mari Matsuzawa, Kadokawa Fujimi Shobo/ImoCho. Production Committee'},
	{'title': 'Saki: Zenkoku-hen','credit': '© 小林 立/スクウェアエニックス・咲全国編製作委員会'},
	{'title': 'Buddy Complex','credit': '©SUNRISE/BUDDY COMPLEX COMMITTEE'},
	{'title': 'Chuunibyou demo Koi ga Shitai!','credit': '© 虎虎／京都アニメーション／中二病でも製作委員会'},
	{'title': 'D-Frag!','credit': '© Tomoya Haruno/PUBLISHED BY KADOKAWA CORPORATION MEDIAFACTORY/D-Fragments Project'},
	{'title': 'Future Card Buddyfight','credit': '© 相棒学園／テレビ愛知'},
	{'title': 'Gin no Saji','credit': '© 荒川弘・小学館／エゾノー祭実行委員会'},
	{'title': 'HappinessCharge Precure!','credit': '©ABC・東映アニメーション'},
	{'title': 'Hamatora','credit': '© カフェノーウェア/ハマトラ製作委員会'},
	{'title': 'Inari, Kon Kon, Koi Iroha','credit': '© 2014 よしだもろへ／KADOKAWA 角川書店刊／いなり製作委員会 / © 京都府 まゆまろ 13176 / © 2013 City of Kyoto. All rights reserved.'},
	{'title': 'Magical Warfare','credit': '© スズキヒサシ／株式会社KADOKAWA　メディアファクトリー刊／すばる魔法学院'},
	{'title': 'Maken-ki Two','credit': '© 2013 Hiromitsu Takeda/PUBLISHED BY KADOKAWA Fujimishobo/MAKEN-KI TWO Partners'},
	{'title': 'Mikakunin DE Shinkoukei','credit': '© 荒井チェリー／一迅社・未確認で進行形製作委員会'},
	{'title': 'Nisekoi','credit': '© 古味直志／集英社・アニプレックス・シャフト・ＭＢＳ'},
	{'title': 'Nobunaga the Fool','credit': '© 河森正治・サテライト／ALC／GP／ノブナガ・ザ・フール製作委員会'},
	{'title': 'Nobunagun','credit': '© 久正人 ／アース・スター エンターテイメント・「ノブナガン製作委員会」'},
	{'title': 'Noragami','credit': '© Adachitoka/Kodansha/Noragami Production Committee'},
	{'title': 'No-rin','credit': '© 2014 白鳥士郎・SBクリエイティブ／のうりんプロジェクト'},
	{'title': 'Saikin, Imouto no Yousu ga Chotto Okashiinda ga.','credit': '© Mari Matsuzawa, Kadokawa Fujimi Shobo/ImoCho. Production Committee'},
	{'title': 'Saki: Zenkoku-hen','credit': '© 小林 立/スクウェアエニックス・咲全国編製作委員会'},
	{'title': 'Sakura Trick','credit': '© タチ・芳文社／桜Trick製作委員会'},
	{'title': 'Seitokai Yakuindomo','credit': '© 氏家ト全・講談社/桜才学園生徒会新室'},
	{'title': 'Sekai Seifuku: Bouryaku no Zvezda','credit': '© hunting cap brothers/Aniplex,Project ZP'},
	{'title': 'Super Sonico the Animation','credit': '© Nitroplus/そにアニProject'},
	{'title': 'Toaru Hikūshi e no Koiuta','credit': '© Koroku Inumura, Shogakukan/Toaru Hikūshi e no Koiuta Project'},
	{'title': 'Wake Up, Girls!','credit': '© Green Leaves / Wake Up, Girls!'},
	{'title': 'Witch Craft Works','credit': '© 水薙竜・講談社／ウィッチクラフトワークス製作委員会'},
	{'title': 'Wizard Barristers - Benmashi Cecil','credit': '© ウィザード・バリスターズ'},
	{'title': 'Z/X Ignition','credit': '© Z/X IGNITION製作委員会'},
	{'title': 'Ameiro Cocoa: Rainy Color e Youkoso!','credit': '© ＩＡＭ電子出版／雨色ココア製作委員会 All Rights Reserved.'},
	{'title': 'Anitore! EX','credit': '© 6pack/あにトレ！EX製作委員会'},
	{'title': 'Brave Beats','credit': '© BNP/ブレイブビーツ製作委員会, メ〜テレ 注意：内容および画像の転載はお断りいたします。お問い合せ先はこちらをご覧ください。'},
	{'title': 'Comet Lucifer','credit': '© Project Felia／「コメット・ルシファー」製作委員会'},
	{'title': 'Concrete Revolutio: Choujin Gensou','credit': '© BONES・會川 昇／コンクリートレボルティオ製作委員会'},
	{'title': 'Dance with Devils','credit': '© グリモワール編纂室／Dance with Devils製作委員会'},
	{'title': 'DD Hokuto no Ken 2: Ichigo Aji+','credit': '© 武論尊・原哲夫／NSP1983，© イチゴ味2015'},
	{'title': 'Diabolik Lovers More, Blood','credit': '© Rejet・IDEA FACTORY／DIABOLIK LOVERS MB PROJECT'},
	{'title': 'Dochamon Junior','credit': ''},
	{'title': 'Doushitemo Eto ni Hairitai','credit': '© Pollyanna Graphics INC. © BAKETAN BLOG All Rights Reserved.'},
	{'title': 'Fushigi na Somera-chan','credit': 'copyright  ©   ちょぼらうにょぽみ/一迅社・野乃本魔法拳道場2015'},
	{'title': 'Fuusen Inu Tinny 2nd Season','credit': '© 2014 Genki Kawamura & Kenjiro Sano / Tinny Project'},
	{'title': 'Gakusen Toshi Asterisk','credit': '© 2015 三屋咲ゆう・株式会社KADOKAWA／アスタリスク製作委員会'},
	{'title': 'Garo: Guren no Tsuki','credit': '© 2015「紅蓮ノ月」 雨宮慶太 / 東北新社'},
	{'title': 'Gochuumon wa Usagi Desu ka??','credit': '© Koi・芳文社／ご注文は製作委員会ですか？？'},
	{'title': 'Hacka Doll the Animation','credit': '© DeNA／ハッカドール THE あにめ～しょん製作委員会'},
	{'title': 'Haikyuu!! Second Season','credit': '© 古舘春一／集英社・「ハイキュー!! セカンドシーズン」製作委員会・MBS'},
	{'title': 'Heavy Object','credit': '© 2015 鎌池和馬／ＫＡＤＯＫＡＷＡ　アスキー・メディアワークス刊／PROJECT HO'},
	{'title': 'Hidan no Aria AA','credit': '© 2015 赤松中学・KADOKAWA刊 / ProjectAA'},
	{'title': 'High School Star Musical','credit': '© ひなた凛／スタミュ製作委員会'},
	{'title': 'Itoshi no Muco','credit': '© みずしな孝之・講談社/いとしのムーコ製作委員会'},
	{'title': 'JK-Meshi!','credit': ''},
	{'title': 'K: Return of Kings','credit': '© GoRA・GoHands／k-project　© Copyright King Record.Co.,Ltd. All Rights Reserved.'},
	{'title': 'Kagewani','credit': '© Copyright Tomovies,LLC / DIRECTIONS,Inc'},
	{'title': 'Kamisama Minarai: Himitsu no Cocotama','credit': 'Copyright© BANDAI Co.LTD. All Rights Reserved. / © BANDAI/TV TOKYO・ここたま製作委員会'},
	{'title': 'Ketsuekigata-kun! 3rd Season','credit': '© LEEONSMART / アース・スター エンターテイメント / 血液型くん! 製作委員会'},
	{'title': 'Kidou Senshi Gundam: Tekketsu no Orphans','credit': '© 創通・サンライズ・MBS'},
	{'title': 'Kindaichi Shounen no Jikenbo Returns (2015)','credit': '© 天樹征丸・さとうふみや・講談社／読売テレビ・東映アニメーション'},
	{'title': 'Komori-san wa Kotowarenai!','credit': ''},
	{'title': 'Kowabon','credit': ''},
	{'title': 'Kyoufu! Zombie Neko','credit': ''},
	{'title': 'Lance N\' Masques','credit': '© 子安秀明/ポニーキャニオン・ProjectLNM'},
	{'title': 'Lupin III - L\'avventura Italiana','credit': '原作 : モンキー・パンチ © TMS'},
	{'title': 'Mini Vanguard 2nd Season','credit': ''},
	{'title': 'Miss Monochrome: The Animation 3','credit': ''},
	{'title': 'Neko Nanka Yondemo Konai.','credit': ''},
	{'title': 'Neko no Dayan: Nihon e Iku','credit': '© Wachifield Licensing Inc. All rights reserved.'},
	{'title': 'Noragami Aragoto','credit': '© あだちとか・講談社 / ノラガミ ARAGOTO製作委員会'},
	{'title': 'One Punch Man','credit': '© ONE・村田雄介／集英社・ヒーロー協会本部'},
	{'title': 'Onsen Yousei Hakone-chan','credit': 'Copyright © 2015 由伊大輔/COMICメテオ/ハコネちゃん製作委員会'},
	{'title': 'Ore ga Ojou-sama Gakkou ni "Shomin Sample" Toshite Gets♥Sareta Ken','credit': '© 七月隆文・閏月戈・一迅社／清華院桜藤会 '},
	{'title': 'Oshiri Kajiri Mushi 4','credit': ''},
	{'title': 'Osomatsu-san','credit': '© 赤塚不二夫／おそ松さん製作委員会'},
	{'title': 'Owari no Seraph: Nagoya Kessen-hen','credit': '© 鏡貴也・山本ヤマト・降矢大輔／集英社・終わりのセラフ製作委員会　© Takaya Kagami, Yamato Yamamoto, Daisuke Furuya/SHUEISHA, Seraph of the End Project'},
	{'title': 'Owarimonogatari','credit': '© 西尾維新／講談社・アニプレックス・シャフト'},
	{'title': 'Peeping Life TV: Season 1??','credit': ''},
	{'title': 'Pokémon XY&Z','credit': '© Nintendo・Creatures・GAME FREAK・TV Tokyo・ShoPro・JR Kikaku © Pokémon'},
	{'title': 'Rakudai Kishi no Cavalry','credit': '© 海空りく・SBクリエイティブ／落第騎士の英雄譚製作委員会'},
	{'title': 'Sakurako-san no Ashimoto ni wa Shitai ga Umatteiru','credit': '© 2015 太田紫織／KADOKAWA／櫻子さん製作委員会'},
	{'title': 'Shin Atashinchi','credit': '© ママレード/KADOKAWA・シンエイ・ADK'},
	{'title': 'Shingeki! Kyojin Chuugakkou','credit': '© 中川沙樹・諫山創・講談社／「進撃！巨人中学校」製作委員会'},
	{'title': 'Shinmai Maou no Testament Burst','credit': '© 2015 上栖 綴人・Nitroplus ／ KADOKAWA　角川書店刊／「新妹魔王の契約者」製作委員会'},
	{'title': 'Soukyuu no Fafner: Dead Aggressor - Exodus 2nd Season','credit': '© XEBEC・FAFNER EXODUS PROJECT ｜ © Copyright King Record.Co.,Ltd. All Right Reserved.'},
	{'title': 'Subete ga F ni Naru: The Perfect Insider','credit': '© 森博嗣・講談社/「すべてがFになる」製作委員会'},
	{'title': 'Taimadou Gakuen 35 Shiken Shoutai','credit': '© 2015 柳実冬貴・切符／ＫＡＤＯＫＡＷＡ／対魔導学園35製作委員会'},	
	{'title': 'Tantei Team KZ Jiken Note','credit': 'Copyright © 2012-2015 SIGNAL.MD. All rights reserved.'},
	{'title': 'Teekyuu','credit': '© ルーツ / Piyo / アース・スター エンターテイメント / 亀井戸高校テニス部'},
	{'title': 'Utawarerumono: Itsuwari no Kamen','credit': '© うたわれるもの偽りの仮面製作委員会'},
	{'title': 'Valkyrie Drive: Mermaid','credit': '© VALKYRIE DRIVE PARTNERS'},
	{'title': 'Young Black Jack','credit': '© ヤング ブラック・ジャック製作委員会'},
	{'title': 'Yuru Yuri Nachuyachumi!+','credit': '© なもり/一迅社・七森中ごらく部'},
	{'title': 'Yuru Yuri San☆Hai!','credit': '© 2015 なもり/一迅社・七森中ごらく部'},	
	{'title': 'K-On!','credit': '© Houbunsha / Kyoto Animation'}
  ];
  $scope.title = "World";
});
