newFunction();
function newFunction() {
	var AniCredits = angular.module('AniCredits', []);

	AniCredits.controller('DisplayPanel', function ($scope) {
		$scope.events = [
			{ 'title': 'Shingeki no Kyojin: The Final Season', 'credit': '©諫山創・講談社／「進撃の巨人」The Final Season製作委員会', 'site': 'https://shingeki.tv/final/' },
			{ 'title': 'Yakusoku no Neverland 2nd Season', 'credit': '©SHUEISHA Inc. All rights reserved.', 'site': 'https://www.shonenjump.com/j/sp_neverland' },
			{ 'title': 'Dr. Stone: Stone Wars', 'credit': '©米スタジオ・Boichi／集英社・Dr.STONE製作委員会', 'site': 'https://dr-stone.jp' },
			{ 'title': 'Tensei shitara Slime Datta Ken 2nd Season', 'credit': '©川上泰樹・伏瀬・講談社／転スラ製作委員会', 'site': 'https://www.ten-sura.com/' },
			{ 'title': 'Horimiya', 'credit': '©HERO・萩原ダイスケ／SQUARE ENIX・「ホリミヤ」製作委員会', 'site': 'https://horimiya-anime.com/' },
			{ 'title': '5-toubun no Hanayome ∬', 'credit': '©春場ねぎ・講談社／「五等分の花嫁∬」製作委員会', 'site': 'http://www.tbs.co.jp/anime/5hanayome/' },
			{ 'title': 'Mushoku Tensei: Isekai Ittara Honki Dasu', 'credit': '©理不尽な孫の手/MFブックス/「無職転生」製作委員会', 'site': 'https://mushokutensei.jp/' },
			{ 'title': 'Beastars 2nd Season', 'credit': '©板垣巴留（秋田書店）／BEASTARS製作委員会', 'site': 'https://bst-anime.com/' },
			{ 'title': 'Kaifuku Jutsushi no Yarinaoshi', 'credit': '©2021 月夜 涙・しおこんぶ／KADOKAWA／回復術士のやり直し製作委員会', 'site': 'http://kaiyari.com/' },
			{ 'title': 'Hataraku Saibou!!', 'credit': '©清水茜／講談社・アニプレックス・davidproduction', 'site': 'https://hataraku-saibou.com/' },
			{ 'title': 'Nanatsu no Taizai: Fundo no Shinpan', 'credit': '', 'site': 'https://horimiya-anime.com/' },
			{ 'title': 'Log Horizon: Entaku Houkai', 'credit': '', 'site': '' },
			{ 'title': 'Hataraku Saibou Black (TV)', 'credit': '', 'site': '' },
			{ 'title': 'Kumo Desu ga, Nani ka?', 'credit': '', 'site': '' },
			{ 'title': 'Wonder Egg Priority', 'credit': '', 'site': '' },
			{ 'title': 'Kemono Jihen', 'credit': '', 'site': '' },
			{ 'title': 'Ore dake Haireru Kakushi Dungeon', 'credit': '', 'site': '' },
			{ 'title': 'SK∞', 'credit': '', 'site': '' },
			{ 'title': 'Yuru Camp△ Season 2', 'credit': '', 'site': '' },
			{ 'title': 'Jaku-Chara Tomozaki-kun', 'credit': '', 'site': '' },
			{ 'title': 'Tatoeba Last Dungeon Mae no Mura no Shounen ga Joban no Machi de Kurasu Youna Monogatari', 'credit': '', 'site': '' },
			{ 'title': 'Urasekai Picnic', 'credit': '', 'site': '' },
			{ 'title': '2.43: Seiin Koukou Danshi Volley-bu', 'credit': '', 'site': 'World Trigger 2nd Season' },
			{ 'title': 'Non Non Biyori Nonstop', 'credit': '', 'site': '' },
			{ 'title': 'Ex-Arm', 'credit': '', 'site': '' },
			{ 'title': 'Bungou Stray Dogs Wan!', 'credit': '', 'site': '' },
			{ 'title': 'Tenchi Souzou Design-bu', 'credit': '', 'site': '' },
			{ 'title': 'Hortensia Saga (TV)', 'credit': '', 'site': '' },
			{ 'title': 'Kai Byoui Ramune', 'credit': '', 'site': '' },
			{ 'title': 'Vlad Love', 'credit': '', 'site': '' },
			{ 'title': 'Back Arrow', 'credit': '', 'site': '' },
			{ 'title': 'Skate-Leading☆Stars', 'credit': '', 'site': '' },
			{ 'title': 'Azur Lane: Bisoku Zenshin!', 'credit': '', 'site': '' },
			{ 'title': 'Project Scard: Praeter no Kizu', 'credit': '', 'site': '' },
			{ 'title': 'Jimihen!!: Jimiko wo Kaechau Jun Isei Kouyuu!!', 'credit': '', 'site': '' },
			{ 'title': 'Uma Musume: Pretty Derby (TV) Season 2', 'credit': '', 'site': '' },
			{ 'title': 'Majutsushi Orphen Hagure Tabi: Kimluck-hen', 'credit': '', 'site': '' },
			{ 'title': 'Wave!!: Surfing Yappe!! (TV)', 'credit': '', 'site': '' },
			{ 'title': 'Idoly Pride', 'credit': '', 'site': '' },
			{ 'title': 'Soukou Musume Senki', 'credit': '', 'site': '' },
			{ 'title': 'Gekidol', 'credit': '', 'site': '' },
			{ 'title': 'I★Chu: Halfway Through the Idol', 'credit': '', 'site': '' },
			{ 'title': 'Yatogame-chan Kansatsu Nikki Sansatsume', 'credit': '', 'site': '' },
			{ 'title': 'WIXOSS Diva(A)Live', 'credit': '', 'site': '' },
			{ 'title': 'Show by Rock!! Stars!!', 'credit': '', 'site': '' },
			{ 'title': 'World Witches Hasshin Shimasu!', 'credit': '', 'site': '' },
			{ 'title': 'Yami Shibai 8', 'credit': '', 'site': '' },
			{ 'title': 'Maiko-san Chi no Makanai-san', 'credit': '', 'site': '' },
			{ 'title': 'Shin Chuuka Ichiban! 2nd Season', 'credit': '', 'site': '' },
			{ 'title': 'Tropical-Rouge! Precure', 'credit': '', 'site': '' },
			{ 'title': 'Abciee Shuugyou Nikki', 'credit': '', 'site': '' },
			{ 'title': 'D4DJ Petit Mix', 'credit': '', 'site': '' },
			{ 'title': 'Kindan Joshi', 'credit': '', 'site': '' },
			{ 'title': 'Okashi na Sabaku no Suna to Manu', 'credit': '', 'site': '' },
			{ 'title': 'One Piece', 'credit': '', 'site': '' },
			{ 'title': 'Black Clover', 'credit': '', 'site': '' },
			{ 'title': 'Jujutsu Kaisen (TV)', 'credit': '', 'site': '' },
			{ 'title': 'Boruto: Naruto Next Generations', 'credit': '', 'site': '' },
			{ 'title': 'Detective Conan', 'credit': '', 'site': '' },
			{ 'title': 'Higurashi no Naku Koro ni Gou', 'credit': '', 'site': '' },
			{ 'title': 'Hanyou no Yashahime: Sengoku Otogizoushi', 'credit': '', 'site': '' },
			{ 'title': 'Crayon Shin-chan', 'credit': '', 'site': '' },
			{ 'title': 'Dragon Quest: Dai no Daibouken (2020)', 'credit': '', 'site': '' },
			{ 'title': 'King\'s Raid: Ishi wo Tsugumono-tachi', 'credit': '', 'site': '' },
			{ 'title': 'Kingdom 3rd Season', 'credit': '', 'site': '' },
			{ 'title': 'Osomatsu-san 3rd Season', 'credit': '', 'site': '' },
			{ 'title': 'Yu☆Gi☆Oh!: Sevens', 'credit': '', 'site': '' },
			{ 'title': 'Shadowverse (TV)', 'credit': '', 'site': '' },
			{ 'title': 'Healin\' Good♡Precure', 'credit': '', 'site': '' },
			{ 'title': 'Sazae-san', 'credit': '', 'site': '' },
			{ 'title': 'Rebirth', 'credit': '', 'site': '' },
			{ 'title': 'Bonobono (TV 2016)', 'credit': '', 'site': '' },
			{ 'title': 'Tokyo Gambo', 'credit': '', 'site': '' },
			{ 'title': 'Bakugan: Armored Alliance', 'credit': '', 'site': '' },
			{ 'title': 'Gal-gaku.: Hijiri Girls Square Gakuin', 'credit': 'Yodel no Onna', 'site': '' },
			{ 'title': 'Kiratto Pri☆chan Season 3', 'credit': '', 'site': '' },
			{ 'title': 'Neko Konogoro', 'credit': '', 'site': '' },
			{ 'title': 'Neko no Robu', 'credit': '', 'site': '' },
			{ 'title': 'Tomica Kizuna Gattai: Earth Granner', 'credit': '', 'site': '' },
			{ 'title': 'Kamiusagi Rope: Warau Asa ni wa Fukuraitaru tte Maji ssuka!?', 'credit': '', 'site': '' },
			{ 'title': 'Seizei Ganbare! Mahou Shoujo Kurumi 3rd Season', 'credit': '', 'site': '' },
			{ 'title': 'Anoyo no Subete wa, Obake-gumi!', 'credit': '', 'site': '' },
			{ 'title': 'Shiawase Haitatsu Taneko', 'credit': '', 'site': '' },
			{ 'title': 'Marumaru Manul', 'credit': '', 'site': '' },
			{ 'title': 'Duel Masters King', 'credit': '', 'site': '' },
			{ 'title': 'Pittanko!! Nekozakana', 'credit': '', 'site': '' },
			{ 'title': 'Manul no Yuube', 'credit': '', 'site': '' },
			{ 'title': 'Kaoru no Taisetsu na Mono', 'credit': '', 'site': '' },
			{ 'title': 'Dinosaur Biyori', 'credit': '', 'site': '' },
			{ 'title': 'Tenkuu Shinpan', 'credit': '', 'site': '' },
			{ 'title': 'Otona no Bouguya-san II', 'credit': '', 'site': '' },
			{ 'title': 'Tian Guan Ci Fu Special', 'credit': '', 'site': '' },
			{ 'title': 'Enen no Shouboutai Mini Anime', 'credit': '', 'site': '' },
			{ 'title': 'Wu Liuqi Zhi Xuanwu Guo Pian', 'credit': '', 'site': '' },
			{ 'title': 'Youjo Shachou', 'credit': '', 'site': '' },
			{ 'title': 'Doki Doki! Mini Mini! Kakushi Dungeon Gekijou', 'credit': '', 'site': '' },
			{ 'title': '2.43 Mini Anime: Inside Story', 'credit': '', 'site': '' },
			{ 'title': '2.43 Mini Anime: Fukui-ben Kouza', 'credit': '', 'site': '' },
			{ 'title': 'Fanren Xiu Xian Chuan Special', 'credit': '', 'site': '' },
			{ 'title': 'Chang Jian Feng Yun', 'credit': '', 'site': '' },
			{ 'title': 'Mashiro no Oto Mini', 'credit': '', 'site': '' },
			{ 'title': 'Jue Ding', 'credit': '', 'site': '' },
			{ 'title': 'Alice in Deadly School', 'credit': '', 'site': '' },
			{ 'title': 'Planetarian: Snow Globe', 'credit': '', 'site': '' },
			{ 'title': 'Saezuru Tori wa Habatakanai: Don\'t Stay Gold', 'credit': '', 'site': '' },
			{ 'title': 'Bean Bandit', 'credit': '', 'site': '' },
			{ 'title': 'Princess Principal: Crown Handler 1', 'credit': '', 'site': '' },
			{ 'title': 'Gintama: The Final', 'credit': '', 'site': '' },
			{ 'title': 'Seitokai Yakuindomo Movie 2', 'credit': '', 'site': '' },
			{ 'title': 'Natsume Yuujinchou: Ishi Okoshi to Ayashiki Raihousha', 'credit': '', 'site': '' },
			{ 'title': 'Bishoujo Senshi Sailor Moon Eternal Movie 1', 'credit': '', 'site': '' },
			{ 'title': 'Girls & Panzer: Saishuushou Part 3', 'credit': '', 'site': '' },
			{ 'title': 'Bishoujo Senshi Sailor Moon Eternal Movie 2', 'credit': '', 'site': '' },
			{ 'title': 'Aria the Crepuscolo', 'credit': '', 'site': '' },
			{ 'title': 'Tokyo 7th Sisters: Bokura wa Aozora ni Naru', 'credit': 'Shin Tennis no Ouji-sama: Hyoutei vs. Rikkai - Game of Future', 'site': '' },
			{ 'title': 'Healin\' Good♡Precure Movie: Yume no Machi de Kyun! Tto GoGo! Dai Henshin!!', 'credit': '', 'site': '' },
			{ 'title': 'Santa Company: Manatsu no Merry Christmas', 'credit': '', 'site': '' },
			{ 'title': 'Gintama: The Semi-Final', 'credit': '', 'site': '' },
			{ 'title': 'Tensei shitara Slime Datta Ken: Kanwa - Hinata Sakaguchi', 'credit': '', 'site': '' },
			{ 'title': 'Dogeza de Tanondemita: Isekai-hen', 'credit': '', 'site': '' },
			{ 'title': 'Re:Zero kara Hajimeru Isekai Seikatsu 2nd Season Part 2', 'credit': '©長月達平・株式会社KADOKAWA刊／Re:ゼロから始める異世界生活2製作委員会', 'site': 'http://re-zero-anime.jp/' }
		];
		$scope.title = "World";
	});
}

